config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, scope: [:list_id]


  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

   validates :name, presence: true
   validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  #has_many :lists, through: :bookmarks
  has_many :bookmarks
  #before_destroy :check_for_bookmarks, prepend: true

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true

#def check_for_bookmarks
    #if bookmarks.count > 0
      #errors.add_to_base("cannot delete customer while orders exist")
      #throw :abort
      #return false
    #end
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

   #GET    /lists/:list_id/bookmarks/new
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new()
  end

#POST   /lists/:list_id/bookmarks
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(strong_params)
    @bookmark.list = @list
    if @bookmark.save
    redirect_to @list
    else
      render :new
    end
  end

#DELETE /bookmarks/:id
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  def strong_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  # GET  /lists/:id
  def show
    @list = List.find(params[:id])
  end
#GET  /lists/new
  def new
    @list = List.new()
  end

  #POST /lists/new
  def create
    @list = List.new(strong_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end
  private

  def strong_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'bookmarks.jpg' %>);">
  <div class="container">
    <h1>Add a bookmark</h1>
  </div>

  <div class="container">
  <%= simple_form_for([ @list, @bookmark ])  do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie%>
    <%= f.submit "Submit bookmark", class: "btn btn-success" %>
  <% end %>
  <br>
  <br>

 <div class="btn btn-success">
  <%= link_to "go back to lists", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'movie_theater.jpg' %>);">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>classic</p>
  </div>
</div>

<div class ="container">
  <h2>Create a new list</h2>
  <div class="btn btn-success btn">
  <%= link_to "+", new_list_path%>
  </div>


  <h2>My lists</h2>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <div>
          <h2><%= link_to "#{list.name}", list_path(list) %></h2>
          <p><%= link_to "add a movie", new_list_bookmark_path(list)%></p>
        </div>
      </div>
    <% end %>
  </div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'couple_theater.jpg' %>);">
  <div class="container">
    <h1>Add a new list</h1>
  </div>
</div>

<div class="container">
  <%= simple_form_for [ @list] do |f| %>
    <%= f.input :name %>
    <%= f.submit "Submit list", class: "btn btn-success" %>
  <% end %>
  <br>
  <br>

 <div class="btn btn-success">
  <%= link_to "go back to lists", root_path %>
</div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'netflix.jpg' %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <% @list.movies.each do |movie| %>
  <h2><%= movie.title %></h2>
  <p><%= movie.overview %></p>
  <% end %>

  <%= link_to "go back to lists", root_path %>
</div>